### ISSUE TITLE
数据迁移文件执行失败

### ISSUE THREAD

**Issue by dan381006472** [lzjcoding/laravel5.4-webpack2-Vuejs2-iview2-spa-demo#1]
数据迁移文件执行失败
![wechatimg93](https://user-images.githubusercontent.com/3352450/29405781-866b1db8-8371-11e7-9ded-6a443afd4bc7.jpeg)

**Comment by lzjcoding** [comment]
你这是ssh登录失败，是不是放错截图？

**Comment by dan381006472** [comment]
额还真是 好逗人..
是这张
![wechatimg97](https://user-images.githubusercontent.com/3352450/29406039-6b91ab00-8372-11e7-8638-b0ee195eb104.jpeg)

**Comment by lzjcoding** [comment]
已经修复，拉取最新代码，删除posts表再重新运行

**Comment by dan381006472** [comment]
ok
